



#test: main.o 
#	g++ main.o -o test

test: main.cpp
	g++  /home/lorin/projects/testboost/libboost_python.so.1.45.0 -lpython2.6  -lboost_python -I/usr/include/python2.6/  main.cpp
#	g++ main.cpp /home/lorin/projects/testboost/libboost_python.so.1.45.0 -lboost_python -lpython2.6 -I/usr/include/python2.6/
