#=================================================================================================
# Ability Class
#
#
# Author - Lorin Beer
# email  - doggerelVerse@gmail.com
#=================================================================================================


#so, what can an ability do?
#  provide bonuses to stats for the purpose of calculating combat
#  provide an alternative calculation for combat
#  provide an effect if attack is successful


#  
#    slash, stab, slam
#    thrust (stab)
#    swing  (slash, slam)
#=================================================================================================
from assets.skills import *
#=================================================================================================
#=================================================================================================
import sys
sys.path.append( "/home/lorin/projects/gelly/objs" )
from actor import Animactor
from action import Action
from effect import Effect
#=================================================================================================
#=================================================================================================
class Skill(object):
  """
    Describes a specific ability available to characters and game objects.

    This description defines the skill's level (the relative strength of the ability), the cost 
    to use, requirements to learn, rules limiting how/when the skill is used, the effect the use 
    of the skill has, etc.   
  """

  levelrange = (0,5)

  def __init__( self, **kwargs ):
    """  
    """
    try:
      self.name  = kwargs['name']  #all skills must have a name, type, level, and threshhold attr
      self.type  = kwargs['atype'] 
      self.level = kwargs['level'] 
      self.threshold = kwargs.get('threshold')
      self.effect = kwargs.get('effect',None) #effect is optional

      #init formulas
      self.__maxenergy_form__  = kwargs.get('maxenergy_formula', DEFAULT_MAXENERGY_FORMULA )
      self.__targetnumber_form__ = kwargs.get('targegnumb_formula',DEFAULT_TARGETNUMBER_FORMULA)
      self.__match_form__ = kwargs.get('match_formula',DEFAULT_MATCH_FORMULA)
      self.__beat_form__ = kwargs.get('beat_formula',DEFAULT_BEAT_FORMULA)
      self.__onsuccess_form__ = kwargs.get('success_formula',DEFAULT_ONSUCCESS_FORMULA)
      self.__onfail_form__ = kwargs.get('fail_formula',DEFAULT_ONFAIL_FORMULA)
    except KeyError:
      print "Neccesary argument for class Skill not present"
      raise KeyError
  #===============================================================================================
  def maxenergy(self):    
    """return the maximum energy useable with this skill"""    
    return self.__maxenergy_form__(self,None)
  #===============================================================================================
  def targetnumber(self,energy):
    """calculate the target number generated by using this skill with given energy value"""
    if energy >= self.threshold:
      return self.__targetnumber_form__( self,None,energy )
    return 0
  #===============================================================================================
  def match(self, targetnumber ): 
    """attempt to match the target number"""
    val = self.__match_form__(self,None,targetnumber)
    return val if (self.threshold <= val and val <= self.maxenergy()) else 0 
  #===============================================================================================
  def beat(self, targetnumber ): 
    """attempt to beat the target number by the minimum amount (1)"""
    val = self.__beat_form__(self,None,targetnumber)
    return val if (self.threshold <= val and val <= self.maxenergy()) else 0 
  #===============================================================================================
  def onsuccess(self):
    """"""
    return self.__onsuccess_form__(self,None)
  #===============================================================================================
  def onfail(self):
    """"""
    return self.__onfail_form__(self,None)
  #===============================================================================================
  def __str__(self):
    """
    """
    return "%s" % (self.name)
#=================================================================================================

import os


class SkillFactory(object):
  """
    Factory class for skills

    Overview:
    To get an instance of a given skill, simply use the skill function
    Skills are created based on templates, the set of all possible skills based on a given
    template is large, and different templates have disjoint sets of possible skills.

    To create a new skill, you simply have to define it in terms of a given template with the
    register_skill function. If the new skill does not fall into an existing template-space, a 
    new template can be defined with the register_template function.

    Templates are implemented as a list, avoiding the need to write code if a new template
    is desired. Each element in the list represents a datamember or function member of skills
    created using this template.
    Example Templates:
      Basic - name: string containing the name of the skill, should be unique
            - level: integer representing the level of this skill
            - threshold: the activation cost of this skill
            - prereqs: list of skill id's representing the prerequisites of this skill
            - effect: the type of effect the use of this skill causes
  """
  def __init__(self):
    """
    """
    #read the data file to register the basic skill types
    self._gfxeffects={'null' : None,
                      'slash': { 'assetpath' :"/home/lorin/projects/ge/art/cut_a",
                                 'framepaths': [] }
                     }
    
    print "init skill factory"
    for k,d in self._gfxeffects.items():
      if d:
        framenames = os.listdir( d['assetpath'] )
        framenames.sort()
        for frame in framenames:
          path = str(os.path.join( d['assetpath'], frame ))
    
          d['framepaths'].append( path )
    print self._gfxeffects['slash']['framepaths']
    eek = Effect( self._gfxeffects['slash']['assetpath'] )
    print eek.done
    self._skilltemplate={ 'slash': {'atype' : 'attack',
                                    'threshold' : 2,
                                    'effect' : eek
                                   },
                          'thrust': {'atype' : 'attack',
                                     'threshold' : 2,
                                     'effect'    : None },
                          'strike': {'atype' : 'attack',
                                     'threshold' : None,
                                     'effect'    : None },
                          'spin':   {'atype'     : 'attack',
                                     'threshold' : None,
                                     'effect'    : None },
                          #DEFENCE SKILLS
                          'parry': { 'atype'     : 'parry',                           
                                     'threshold' : 3,
                                     'effect'    : None },

                          'dodge': { 'atype'     : 'dodge',
                                     'threshold' : 3,
                                     'effect'    : None }                                  
                          }
  #===============================================================================================
  def makeskill(self,sid,level=0):
    """
    """
    if sid not in self._skilltemplate: return False
    sk = self._skilltemplate[sid]
    sk['name']=sid
    sk['level']=level
    return Skill( **(sk) )
  #===============================================================================================
  def register_skill(self, template, **kwargs ):
    """
      Register a new skill with the factory.
    """
  #===============================================================================================
  def register_template(self):
    """
      Register a new skill template with the factory.

      A skill template is a pattern for creating a wide range of individual skills.
      Registering a new template should only be done if the current space of skills that can be
      created with existing templates does not cover a new desired skill
    """
  #===============================================================================================
